version: '3.9'
services:
# KAFKA -------------------------------------------------------------------------------
  zoo1:
    image: cfei/zookeeper:latest-multiarch
    container_name: zoo1
    restart: on-failure
    labels:
      - com.centurylinklabs.watchtower.enable="false"
    ports:
      - 2181:2181
    environment:
      ZOO_ID: 1
      TZ: Europe/Copenhagen
      ZOO_PORT: 2181
      ZOO_SERVERS: server.1=0.0.0.0:2888:3888
    networks:
      - i4net
    profiles:
      - kafka

  kafka1:
    image: cfei/kafka:latest-multiarch
    container_name: kafka1
    restart: on-failure
    labels:
      - com.centurylinklabs.watchtower.enable="false"
    ports:
      - 9091:9091
      - 9092:9092
    environment:
      KAFKA_BROKER_ID: 1
      TZ: Europe/Copenhagen
      KAFKA_ZOOKEEPER_CONNECT: zoo1:2181/kafka
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT,DOCKER_LISTENER:PLAINTEXT"
      KAFKA_LISTENERS: INTERNAL://0.0.0.0:9091,EXTERNAL://0.0.0.0:9092,DOCKER_LISTENER://0.0.0.0:19092
      KAFKA_ADVERTISED_LISTENERS: "INTERNAL://kafka1:9091,EXTERNAL://${HOST_DNS}:9092,DOCKER_LISTENER://kafka1:19092"
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_HEAP_OPTS: "-Xmx${KAFKA_RAM}G"
      KAFKA_HEALTHCHECK_PORT: 9091
      KAFKA_CREATE_TOPICS: "connect-offsets:1:1:compact"
    depends_on:
      - zoo1
    extra_hosts:
      - host.docker.internal:host-gateway
    volumes: 
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
    networks:
      - i4net
    profiles:
      - kafka
  kowl:
    image: quay.io/cloudhut/kowl:master
    ports:
      - 8088:8080
    environment:
      KAFKA_BROKERS: kafka1:19092
    restart: always
    depends_on: 
      - "kafka1"
    profiles:
      - kafka
    networks:
      - i4net
networks:
  i4net:
    name: i4net
    driver: bridge

